// Regenerate `src/lib/pdfFont.generated.ts` from the Arimo webfont package.
//
// Why this exists: the PDF export must look like the house style, which is
// 9 pt Arial. Arial itself cannot be embedded (licensed), so we embed Arimo —
// metric-compatible with Arial (identical advance widths, so line breaks and
// text extents match) and near-identical in shape. Arimo is SIL OFL 1.1, which
// permits embedding.
//
// Why a conversion step: jsPDF embeds TrueType, and @fontsource ships WOFF.
// WOFF v1 is just an sfnt whose tables are individually zlib-deflated, so
// rebuilding the TTF is a mechanical unpack — no font library needed.
//
// Run with `npm run build:fonts` after bumping @fontsource/arimo. The output is
// committed so a normal build never has to do this.

import { inflateSync } from 'node:zlib';
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));

/** WOFF v1 → TTF. Throws on anything that is not a plain WOFF. */
function woffToTtf(woff) {
  if (woff.readUInt32BE(0) !== 0x774f4646) throw new Error('not a WOFF (bad signature)');
  const flavor = woff.readUInt32BE(4);
  // 'OTTO' means CFF outlines, which jsPDF cannot embed — writing one out with a
  // .ttf name would produce a font that silently fails at export time.
  if (flavor === 0x4f54544f) throw new Error('CFF/OpenType (OTTO) flavour; jsPDF needs TrueType outlines');
  const numTables = woff.readUInt16BE(12);
  if (numTables === 0) throw new Error('no tables in the WOFF');

  const entries = [];
  for (let i = 0; i < numTables; i++) {
    const p = 44 + i * 20;
    entries.push({
      tag: woff.readUInt32BE(p),
      offset: woff.readUInt32BE(p + 4),
      compLength: woff.readUInt32BE(p + 8),
      origLength: woff.readUInt32BE(p + 12),
      checksum: woff.readUInt32BE(p + 16),
    });
  }

  // A table is stored deflated only when that made it smaller; equal lengths
  // mean it was stored raw.
  const tables = entries.map((e) => {
    const raw = woff.subarray(e.offset, e.offset + e.compLength);
    const data = e.compLength < e.origLength ? inflateSync(raw) : raw;
    if (data.length !== e.origLength) {
      throw new Error(`table length mismatch: got ${data.length}, want ${e.origLength}`);
    }
    return { ...e, data };
  });

  const headerLen = 12 + numTables * 16;
  const padded = (n) => (n + 3) & ~3;
  const totalLen = tables.reduce((n, t) => n + padded(t.data.length), headerLen);
  const out = Buffer.alloc(totalLen);

  // sfnt header. The binary-search fields are derived from numTables and must
  // be present even though every reader ignores them in practice.
  const pow2 = 2 ** Math.floor(Math.log2(numTables));
  out.writeUInt32BE(flavor, 0);
  out.writeUInt16BE(numTables, 4);
  out.writeUInt16BE(pow2 * 16, 6);
  out.writeUInt16BE(Math.log2(pow2), 8);
  out.writeUInt16BE(numTables * 16 - pow2 * 16, 10);

  let dataPos = headerLen;
  let headOffset = -1;
  tables.forEach((t, i) => {
    const rec = 12 + i * 16;
    out.writeUInt32BE(t.tag, rec);
    out.writeUInt32BE(t.checksum, rec + 4);
    out.writeUInt32BE(dataPos, rec + 8);
    out.writeUInt32BE(t.data.length, rec + 12);
    t.data.copy(out, dataPos);
    if (t.tag === 0x68656164) headOffset = dataPos;   // 'head'
    dataPos += padded(t.data.length);      // the gap is already zero-filled
  });

  // head.checkSumAdjustment covers the WHOLE file, so it only becomes valid
  // once the tables have been laid out at their new offsets. Copying the WOFF's
  // value leaves it stale: browsers and jsPDF ignore it, but strict validators
  // and OS font installers do not.
  if (headOffset >= 0) {
    out.writeUInt32BE(0, headOffset + 8);             // zero it before summing
    let sum = 0;
    for (let i = 0; i + 3 < out.length; i += 4) sum = (sum + out.readUInt32BE(i)) >>> 0;
    out.writeUInt32BE((0xb1b0afba - sum) >>> 0, headOffset + 8);
  }
  return out;
}

const faces = [
  { file: 'arimo-latin-400-normal.woff', varName: 'ARIMO_REGULAR_B64', style: 'normal' },
  { file: 'arimo-latin-700-normal.woff', varName: 'ARIMO_BOLD_B64', style: 'bold' },
];

let body = '';
for (const f of faces) {
  const woff = readFileSync(`${root}node_modules/@fontsource/arimo/files/${f.file}`);
  const ttf = woffToTtf(woff);
  console.log(`${f.file}: ${woff.length} B woff → ${ttf.length} B ttf`);
  const b64 = ttf.toString('base64');
  // 96 chars per line keeps the generated file diffable and under any editor's
  // line-length limits.
  const wrapped = (b64.match(/.{1,96}/g) ?? []).map((l) => `  '${l}'`).join(' +\n');
  body += `\nexport const ${f.varName} =\n${wrapped};\n`;
}

const header = `// GENERATED by scripts/build-fonts.mjs — do not edit by hand.
//
// Arimo (SIL OFL 1.1, https://github.com/googlefonts/arimo), latin subset,
// converted from @fontsource/arimo's WOFF to the TrueType jsPDF embeds.
//
// Arimo is metric-compatible with Arial: same advance widths, so a 9 pt line
// occupies exactly the width it would in Arial, and near-identical letterforms.
// Arial itself is licensed and cannot be embedded.
//
// Regenerate with \`npm run build:fonts\`.
`;

writeFileSync(`${root}src/lib/pdfFont.generated.ts`, header + body);
console.log('wrote src/lib/pdfFont.generated.ts');
