import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
// Floating map controls — replaces Leaflet's default zoom widget with a
// richer panel: zoom, pan (4-way), home (fit calc area), layer toggle (drops
// a small popover), 3D placeholder.
import { useState } from 'react';
export function MapControls(props) {
    const [layerOpen, setLayerOpen] = useState(false);
    return (_jsxs("div", { className: "map-controls", children: [_jsxs("div", { className: "map-controls-group zoom", children: [_jsx("button", { title: "Zoom in", onClick: props.onZoomIn, children: "\uFF0B" }), _jsx("button", { title: "Zoom out", onClick: props.onZoomOut, children: "\u2212" })] }), _jsxs("div", { className: "map-controls-group pan", children: [_jsx("div", {}), _jsx("button", { title: "Pan north", onClick: () => props.onPan(0, -120), children: "\u25B2" }), _jsx("div", {}), _jsx("button", { title: "Pan west", onClick: () => props.onPan(-120, 0), children: "\u25C0" }), _jsx("button", { title: "Home (fit calc area)", onClick: props.onHome, children: "\u2302" }), _jsx("button", { title: "Pan east", onClick: () => props.onPan(120, 0), children: "\u25B6" }), _jsx("div", {}), _jsx("button", { title: "Pan south", onClick: () => props.onPan(0, 120), children: "\u25BC" }), _jsx("div", {})] }), _jsxs("div", { className: "map-controls-group layers", children: [_jsx("button", { title: "Layers", onClick: () => setLayerOpen((v) => !v), children: "\u2261" }), layerOpen && (_jsxs("div", { className: "map-layer-popover map-chrome", children: [_jsx("div", { className: "chrome-title", children: "Base map" }), _jsx("button", { className: `btn small block${props.baseMap === 'satellite' ? ' active' : ''}`, onClick: () => { props.setBaseMap('satellite'); setLayerOpen(false); }, children: "Satellite" }), _jsx("button", { className: `btn small block${props.baseMap === 'osm' ? ' active' : ''}`, onClick: () => { props.setBaseMap('osm'); setLayerOpen(false); }, children: "OpenStreetMap" }), _jsx("button", { className: "btn small block", disabled: true, title: "3D view \u2014 coming next iteration", children: "3D (TBD)" })] }))] })] }));
}
